name: bad-pods
channels:
  - nvidia
  - conda-forge
dependencies:
  # Core dependencies
  - cudatoolkit
  - python>=3.9
  - numpy >=1.24.0
  - scipy >=1.10.0

  # Visualization and experiment tracking
  - matplotlib >=3.7.0
  - wandb >=0.15.0
  - tensorboard >=2.15.0

  # Development and profiling tools
  - tqdm >=4.65.0
  - jupyter >=1.0.0
  - ipykernel >=6.0.0
  - psutil >=5.9.0
  - line_profiler >=4.0.0
  - pytest >=7.3.1

  # Optional - uncomment as needed
  # - optax >=0.1.7  # JAX optimization library
  # - flax >=0.7.5   # JAX neural network library
  # - chex >=0.1.7   # JAX testing utilities
  # - tensorflow >=2.13.0  # For full TensorBoard profiling features

  # Additional utilities
  - debugpy >=1.6.7
  - rich >=13.4.2

  # JAX with CUDA support 
  - pip
  - pip:
    - "jax[cuda12]>=0.4.20"  # For CUDA 12.x
  #  # OR
  #  # - "jax[cuda11]>=0.4.20"  # For CUDA 11.x

  # Standard JAX packages (these or CUDA version)
  #- jax >=0.4.20
  #- jaxlib >=0.4.20
